//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardHeader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardHeader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Web.Resources.CardHeader", typeof(CardHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Events ({0}).
        /// </summary>
        internal static string EventAvailableEvents {
            get {
                return ResourceManager.GetString("EventAvailableEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Events.
        /// </summary>
        internal static string EventMyEvents {
            get {
                return ResourceManager.GetString("EventMyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string IndexApple {
            get {
                return ResourceManager.GetString("IndexApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        internal static string IndexDiamond {
            get {
                return ResourceManager.GetString("IndexDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights of the Week ({0}).
        /// </summary>
        internal static string IndexHighlights {
            get {
                return ResourceManager.GetString("IndexHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        internal static string IndexPopularity {
            get {
                return ResourceManager.GetString("IndexPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string IndexRanking {
            get {
                return ResourceManager.GetString("IndexRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ProfileAccountActions {
            get {
                return ResourceManager.GetString("ProfileAccountActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Data.
        /// </summary>
        internal static string ProfileAccountRegistrationData {
            get {
                return ResourceManager.GetString("ProfileAccountRegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileData {
            get {
                return ResourceManager.GetString("ProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Photo.
        /// </summary>
        internal static string ProfileGaleryMainPhoto {
            get {
                return ResourceManager.GetString("ProfileGaleryMainPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string ProfileGaleryPhotoGallery {
            get {
                return ResourceManager.GetString("ProfileGaleryPhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string ProfileIndexAchievements {
            get {
                return ResourceManager.GetString("ProfileIndexAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions.
        /// </summary>
        internal static string ProfileIndexInteractions {
            get {
                return ResourceManager.GetString("ProfileIndexInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string ProfilePreferences {
            get {
                return ResourceManager.GetString("ProfilePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string SupportErrors {
            get {
                return ResourceManager.GetString("SupportErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement Suggestions.
        /// </summary>
        internal static string SupportImprovementSuggestions {
            get {
                return ResourceManager.GetString("SupportImprovementSuggestions", resourceCulture);
            }
        }
    }
}
