//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileLifestyleModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileLifestyleModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Model.ProfileLifestyleModel", typeof(ProfileLifestyleModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string CareerCluster_Name {
            get {
                return ResourceManager.GetString("CareerCluster_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most common option selected automatically (applicable to most people).
        /// </summary>
        public static string Diet_Description {
            get {
                return ResourceManager.GetString("Diet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        public static string Diet_Name {
            get {
                return ResourceManager.GetString("Diet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        public static string Drink_Name {
            get {
                return ResourceManager.GetString("Drink_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationLevel_Name {
            get {
                return ResourceManager.GetString("EducationLevel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Kids.
        /// </summary>
        public static string HaveChildren_Name {
            get {
                return ResourceManager.GetString("HaveChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any doubts, you can take a test on the original website (English only).
        /// </summary>
        public static string LoveLanguage_Description {
            get {
                return ResourceManager.GetString("LoveLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love Language.
        /// </summary>
        public static string LoveLanguage_Name {
            get {
                return ResourceManager.GetString("LoveLanguage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any doubts, you can take a test on the original website (English only).
        /// </summary>
        public static string MoneyPersonality_Description {
            get {
                return ResourceManager.GetString("MoneyPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Personality.
        /// </summary>
        public static string MoneyPersonality_Name {
            get {
                return ResourceManager.GetString("MoneyPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to test on a third-party site (multi-language).
        /// </summary>
        public static string MyersBriggsTypeIndicator_Description {
            get {
                return ResourceManager.GetString("MyersBriggsTypeIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBTI Personality.
        /// </summary>
        public static string MyersBriggsTypeIndicator_Name {
            get {
                return ResourceManager.GetString("MyersBriggsTypeIndicator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If in doubt, you can take a test on a third-party site (English only).
        /// </summary>
        public static string RelationshipPersonality_Description {
            get {
                return ResourceManager.GetString("RelationshipPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality in Relationship.
        /// </summary>
        public static string RelationshipPersonality_Name {
            get {
                return ResourceManager.GetString("RelationshipPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion_Name {
            get {
                return ResourceManager.GetString("Religion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any doubts, you can take a test on the original website (English only).
        /// </summary>
        public static string SexPersonality_Description {
            get {
                return ResourceManager.GetString("SexPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Personality.
        /// </summary>
        public static string SexPersonality_Name {
            get {
                return ResourceManager.GetString("SexPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike other personalities, this one&apos;s compatibility is a personal preference..
        /// </summary>
        public static string SexPersonalityPreferences_Description {
            get {
                return ResourceManager.GetString("SexPersonalityPreferences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Personality.
        /// </summary>
        public static string SexPersonalityPreferences_Name {
            get {
                return ResourceManager.GetString("SexPersonalityPreferences_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        public static string Smoke_Name {
            get {
                return ResourceManager.GetString("Smoke_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting the Bills.
        /// </summary>
        public static string SplitTheBill_Name {
            get {
                return ResourceManager.GetString("SplitTheBill_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want Kids.
        /// </summary>
        public static string WantChildren_Name {
            get {
                return ResourceManager.GetString("WantChildren_Name", resourceCulture);
            }
        }
    }
}
