//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileLifestyleModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileLifestyleModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Model.ProfileLifestyleModel", typeof(ProfileLifestyleModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carreira.
        /// </summary>
        internal static string CareerCluster_Name {
            get {
                return ResourceManager.GetString("CareerCluster_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção mais comum selecionada automaticamente (aplicável para a maioria das pessoas).
        /// </summary>
        internal static string Diet_Description {
            get {
                return ResourceManager.GetString("Diet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieta.
        /// </summary>
        internal static string Diet_Name {
            get {
                return ResourceManager.GetString("Diet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe.
        /// </summary>
        internal static string Drink_Name {
            get {
                return ResourceManager.GetString("Drink_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educação.
        /// </summary>
        internal static string EducationLevel_Name {
            get {
                return ResourceManager.GetString("EducationLevel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem Filho(s).
        /// </summary>
        internal static string HaveChildren_Name {
            get {
                return ResourceManager.GetString("HaveChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso tenha dúvidas, poderá fazer um teste no site original (somente em inglês).
        /// </summary>
        internal static string LoveLanguage_Description {
            get {
                return ResourceManager.GetString("LoveLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguagem do Amor.
        /// </summary>
        internal static string LoveLanguage_Name {
            get {
                return ResourceManager.GetString("LoveLanguage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso tenha dúvidas, poderá fazer um teste no site original (somente em inglês).
        /// </summary>
        internal static string MoneyPersonality_Description {
            get {
                return ResourceManager.GetString("MoneyPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalidade Financeira.
        /// </summary>
        internal static string MoneyPersonality_Name {
            get {
                return ResourceManager.GetString("MoneyPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo é opcional (é necessário fazer um teste em site de terceiros / multi-idiomas).
        /// </summary>
        internal static string MyersBriggsTypeIndicator_Description {
            get {
                return ResourceManager.GetString("MyersBriggsTypeIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalidade MBTI.
        /// </summary>
        internal static string MyersBriggsTypeIndicator_Name {
            get {
                return ResourceManager.GetString("MyersBriggsTypeIndicator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso tenha dúvidas, poderá fazer um teste em site de terceiros (somente em inglês).
        /// </summary>
        internal static string RelationshipPersonality_Description {
            get {
                return ResourceManager.GetString("RelationshipPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalidade na Relação.
        /// </summary>
        internal static string RelationshipPersonality_Name {
            get {
                return ResourceManager.GetString("RelationshipPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religião.
        /// </summary>
        internal static string Religion_Name {
            get {
                return ResourceManager.GetString("Religion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso tenha dúvidas, poderá fazer um teste no site original (somente em inglês).
        /// </summary>
        internal static string SexPersonality_Description {
            get {
                return ResourceManager.GetString("SexPersonality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalidade Sexual.
        /// </summary>
        internal static string SexPersonality_Name {
            get {
                return ResourceManager.GetString("SexPersonality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferentemente das outras personalidades, a compatibilidade desta é uma preferência pessoal.
        /// </summary>
        internal static string SexPersonalityPreferences_Description {
            get {
                return ResourceManager.GetString("SexPersonalityPreferences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person. Sexual (Preferências).
        /// </summary>
        internal static string SexPersonalityPreferences_Name {
            get {
                return ResourceManager.GetString("SexPersonalityPreferences_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuma.
        /// </summary>
        internal static string Smoke_Name {
            get {
                return ResourceManager.GetString("Smoke_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividindo as Contas.
        /// </summary>
        internal static string SplitTheBill_Name {
            get {
                return ResourceManager.GetString("SplitTheBill_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quer Filho(s).
        /// </summary>
        internal static string WantChildren_Name {
            get {
                return ResourceManager.GetString("WantChildren_Name", resourceCulture);
            }
        }
    }
}
