//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileBasicModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileBasicModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Model.ProfileBasicModel", typeof(ProfileBasicModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo Biológico.
        /// </summary>
        internal static string BiologicalSex_Name {
            get {
                return ResourceManager.GetString("BiologicalSex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação Atual.
        /// </summary>
        internal static string CurrentSituation_Name {
            get {
                return ResourceManager.GetString("CurrentSituation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Description_Name {
            get {
                return ResourceManager.GetString("Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para sua própria segurança, favor não incluir informações de contato (celular, email, etc.) ou da sua localização (onde está ou já esteve). \n\nOBS: Promover redes sociais, produtos, serviços e/ou conteúdos que violem direitos de terceiros estará sujeito a banimento da plataforma..
        /// </summary>
        internal static string Description_Prompt {
            get {
                return ResourceManager.GetString("Description_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção mais comum selecionada automaticamente (aplicável para a maioria das pessoas).
        /// </summary>
        internal static string GenderIdentity_Description {
            get {
                return ResourceManager.GetString("GenderIdentity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidade de Gênero.
        /// </summary>
        internal static string GenderIdentity_Name {
            get {
                return ResourceManager.GetString("GenderIdentity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De acordo com a seleção, poderá alterar os campos disponíveis e/ou obrigatórios (escolha até 2 opções).
        /// </summary>
        internal static string Intentions_Description {
            get {
                return ResourceManager.GetString("Intentions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenções.
        /// </summary>
        internal static string Intentions_Name {
            get {
                return ResourceManager.GetString("Intentions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolhido automaticamente de acordo com os idiomas oficiais do pais (caso disponível).
        /// </summary>
        internal static string Languages_Description {
            get {
                return ResourceManager.GetString("Languages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        internal static string Languages_Name {
            get {
                return ResourceManager.GetString("Languages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação automática (deve-se liberar acesso a localização do aparelho).
        /// </summary>
        internal static string Location_Description {
            get {
                return ResourceManager.GetString("Location_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor clicar no botão ao lado.
        /// </summary>
        internal static string Location_Prompt {
            get {
                return ResourceManager.GetString("Location_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome / Apelido.
        /// </summary>
        internal static string NickName_Name {
            get {
                return ResourceManager.GetString("NickName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: Paulo ou Paulinho.
        /// </summary>
        internal static string NickName_Prompt {
            get {
                return ResourceManager.GetString("NickName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção mais comum selecionada automaticamente (aplicável para a maioria das pessoas).
        /// </summary>
        internal static string SexualOrientation_Description {
            get {
                return ResourceManager.GetString("SexualOrientation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientação Sexual.
        /// </summary>
        internal static string SexualOrientation_Name {
            get {
                return ResourceManager.GetString("SexualOrientation_Name", resourceCulture);
            }
        }
    }
}
