//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileBasicModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileBasicModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Model.ProfileBasicModel", typeof(ProfileBasicModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological Sex.
        /// </summary>
        public static string BiologicalSex_Name {
            get {
                return ResourceManager.GetString("BiologicalSex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Situation.
        /// </summary>
        public static string CurrentSituation_Name {
            get {
                return ResourceManager.GetString("CurrentSituation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Name {
            get {
                return ResourceManager.GetString("Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your own safety, please do not include contact information (mobile, email, etc.) or your location (where you are or have been). \n\nNOTE: Promoting social networks, products, services and/or content that violates the rights of third parties will be subject to banishment from the platform..
        /// </summary>
        public static string Description_Prompt {
            get {
                return ResourceManager.GetString("Description_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most common option selected automatically (applicable to most people).
        /// </summary>
        public static string GenderIdentity_Description {
            get {
                return ResourceManager.GetString("GenderIdentity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Identity.
        /// </summary>
        public static string GenderIdentity_Name {
            get {
                return ResourceManager.GetString("GenderIdentity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the selection, you can change the mandatory fields (choose up to 2 options).
        /// </summary>
        public static string Intentions_Description {
            get {
                return ResourceManager.GetString("Intentions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentions.
        /// </summary>
        public static string Intentions_Name {
            get {
                return ResourceManager.GetString("Intentions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically chosen according to the official languages of the country (if available).
        /// </summary>
        public static string Languages_Description {
            get {
                return ResourceManager.GetString("Languages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages_Name {
            get {
                return ResourceManager.GetString("Languages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t store your GPS location, just your city. (Access to device location must be released).
        /// </summary>
        public static string Location_Description {
            get {
                return ResourceManager.GetString("Location_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the button to the side.
        /// </summary>
        public static string Location_Prompt {
            get {
                return ResourceManager.GetString("Location_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality.
        /// </summary>
        public static string Modality_Name {
            get {
                return ResourceManager.GetString("Modality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string NickName_Name {
            get {
                return ResourceManager.GetString("NickName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: Paul.
        /// </summary>
        public static string NickName_Prompt {
            get {
                return ResourceManager.GetString("NickName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most common option selected automatically (applicable to most people).
        /// </summary>
        public static string SexualOrientation_Description {
            get {
                return ResourceManager.GetString("SexualOrientation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Orientation.
        /// </summary>
        public static string SexualOrientation_Name {
            get {
                return ResourceManager.GetString("SexualOrientation_Name", resourceCulture);
            }
        }
    }
}
