//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurrentSituation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrentSituation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.CurrentSituation", typeof(CurrentSituation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship with only one partner at a time. A monogamous relationship can be sexual or emotional, usually both..
        /// </summary>
        internal static string Monogamous_Description {
            get {
                return ResourceManager.GetString("Monogamous_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commited (Monogamous).
        /// </summary>
        internal static string Monogamous_Name {
            get {
                return ResourceManager.GetString("Monogamous_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basically, non-monogamy is a category used to describe any relationship that isn’t monogamous. So, a couple who have an open relationship, or a couple who are polyamorous are examples. It’s important to mention that somebody being unfaithful to their partner isn’t non-monogamy – that’s infidelity. For non-monogamy to be applied, both partners must agree that this is something they want to participate in, and both feel comfortable with..
        /// </summary>
        internal static string NonMonogamous_Description {
            get {
                return ResourceManager.GetString("NonMonogamous_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commited (Non-monogamous).
        /// </summary>
        internal static string NonMonogamous_Name {
            get {
                return ResourceManager.GetString("NonMonogamous_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of relationship where the person is not involved in any kind of love and/or sexual bond..
        /// </summary>
        internal static string Single_Description {
            get {
                return ResourceManager.GetString("Single_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Single_Name {
            get {
                return ResourceManager.GetString("Single_Name", resourceCulture);
            }
        }
    }
}
