//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Diet", typeof(Diet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detox and/or weight loss diet can be combined with other diets to detox the body of toxins and/or lose weight..
        /// </summary>
        internal static string DetoxWeightLoss_Description {
            get {
                return ResourceManager.GetString("DetoxWeightLoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detox / Weight Loss.
        /// </summary>
        internal static string DetoxWeightLoss_Name {
            get {
                return ResourceManager.GetString("DetoxWeightLoss_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flexitarian diet is in between omnivore and vegetarian. It’s someone who eats a mostly vegetarian diet, with the exception of a few animal meats. It’s also referred to as the semi-vegetarian diet..
        /// </summary>
        internal static string Flexitarian_Description {
            get {
                return ResourceManager.GetString("Flexitarian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexitarian.
        /// </summary>
        internal static string Flexitarian_Name {
            get {
                return ResourceManager.GetString("Flexitarian_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gluten free diet is essentially eliminating gluten from food. Gluten is a type of protein commonly found in wheat and other grains..
        /// </summary>
        internal static string GlutenFree_Description {
            get {
                return ResourceManager.GetString("GlutenFree_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluten Free.
        /// </summary>
        internal static string GlutenFree_Name {
            get {
                return ResourceManager.GetString("GlutenFree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The omnivore diet consists of animal products and meat, as well as fruits and vegetables. It essentially means that one can eat everything and nothing is limited to them..
        /// </summary>
        internal static string Omnivore_Description {
            get {
                return ResourceManager.GetString("Omnivore_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnivore.
        /// </summary>
        internal static string Omnivore_Name {
            get {
                return ResourceManager.GetString("Omnivore_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organic, all natural, and/or local food diet consists of all or mostly organic foods and/or made locally, often by small businesses or farms..
        /// </summary>
        internal static string OrganicAllnaturalLocal_Description {
            get {
                return ResourceManager.GetString("OrganicAllnaturalLocal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic / All Natural / Local.
        /// </summary>
        internal static string OrganicAllnaturalLocal_Name {
            get {
                return ResourceManager.GetString("OrganicAllnaturalLocal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The raw food diet consists of only fresh, uncooked fruits, vegetables, nuts, and/or seeds. In other words, it’s pure raw and doesn’t contain any processed foods which often lose their nutritional value..
        /// </summary>
        internal static string RawFood_Description {
            get {
                return ResourceManager.GetString("RawFood_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Food.
        /// </summary>
        internal static string RawFood_Name {
            get {
                return ResourceManager.GetString("RawFood_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vegan diet is similar to the vegetarian diet in that it does not include any animal meat. But, it also doesn’t include any animal products at all..
        /// </summary>
        internal static string Vegan_Description {
            get {
                return ResourceManager.GetString("Vegan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan.
        /// </summary>
        internal static string Vegan_Name {
            get {
                return ResourceManager.GetString("Vegan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vegetarian diet consists of no animal meat, but includes other animal products, such as dairy, like milk, cheese, yogurt, and can even sometimes include eggs or not..
        /// </summary>
        internal static string Vegetarian_Description {
            get {
                return ResourceManager.GetString("Vegetarian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        internal static string Vegetarian_Name {
            get {
                return ResourceManager.GetString("Vegetarian_Name", resourceCulture);
            }
        }
    }
}
