//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Disability {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Disability() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Disability", typeof(Disability).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Deaf” describes an individual who has severe to profound hearing loss. “Deafened” describes an individual who has acquired a hearing loss in adulthood..
        /// </summary>
        internal static string Hearing_Description {
            get {
                return ResourceManager.GetString("Hearing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing.
        /// </summary>
        internal static string Hearing_Name {
            get {
                return ResourceManager.GetString("Hearing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characterized by intellectual development and capacity that is significantly below average. Involves a permanent limitation in a person’s ability to learn..
        /// </summary>
        internal static string Intellectual_Description {
            get {
                return ResourceManager.GetString("Intellectual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellectual.
        /// </summary>
        internal static string Intellectual_Name {
            get {
                return ResourceManager.GetString("Intellectual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A learning disability is essentially a specific and persistent disorder of a person’s central nervous system affecting the learning process. This impacts a person’s ability to either interpret what they see and hear, or to link information from different parts of the brain..
        /// </summary>
        internal static string Learning_Description {
            get {
                return ResourceManager.GetString("Learning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning.
        /// </summary>
        internal static string Learning_Name {
            get {
                return ResourceManager.GetString("Learning_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental health disabilities can take many forms, just as physical disabilities do. They are generally classified into six categories: Schizophrenia, Mood Disorders, Anxiety Disorders, Eating Disorders, Personality Disorders, Organic Brain Disorders..
        /// </summary>
        internal static string MentalHealth_Description {
            get {
                return ResourceManager.GetString("MentalHealth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health.
        /// </summary>
        internal static string MentalHealth_Name {
            get {
                return ResourceManager.GetString("MentalHealth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes physiological, functional and/or mobility impairments. Can be fluctuating or intermittent, chronic, progressive or stable, visible or invisible..
        /// </summary>
        internal static string Physical_Description {
            get {
                return ResourceManager.GetString("Physical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        internal static string Physical_Name {
            get {
                return ResourceManager.GetString("Physical_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Legally Blind” describes an individual who has 10% or less of normal vision. Only 10% of people with a visual disability are actually totally blind. The other 90% are described as having a “Visual Impairment.”.
        /// </summary>
        internal static string Visual_Description {
            get {
                return ResourceManager.GetString("Visual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string Visual_Name {
            get {
                return ResourceManager.GetString("Visual_Name", resourceCulture);
            }
        }
    }
}
