//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Drink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Drink() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Drink", typeof(Drink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not consume any type of alcoholic beverage.
        /// </summary>
        internal static string No_Description {
            get {
                return ResourceManager.GetString("No_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Name {
            get {
                return ResourceManager.GetString("No_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the person who drinks at least twice a week.
        /// </summary>
        internal static string YesHeavy_Description {
            get {
                return ResourceManager.GetString("YesHeavy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, often.
        /// </summary>
        internal static string YesHeavy_Name {
            get {
                return ResourceManager.GetString("YesHeavy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the person who drinks rarely and/or only on social occasions, not exceeding twice a month.
        /// </summary>
        internal static string YesLight_Description {
            get {
                return ResourceManager.GetString("YesLight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, socially.
        /// </summary>
        internal static string YesLight_Name {
            get {
                return ResourceManager.GetString("YesLight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the person who drinks approximately once a week, up to six times a month.
        /// </summary>
        internal static string YesModerate_Description {
            get {
                return ResourceManager.GetString("YesModerate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, moderately.
        /// </summary>
        internal static string YesModerate_Name {
            get {
                return ResourceManager.GetString("YesModerate_Name", resourceCulture);
            }
        }
    }
}
