//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Food {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Food() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Food", typeof(Food).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Food.
        /// </summary>
        internal static string AmericanFood {
            get {
                return ResourceManager.GetString("AmericanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentinian Food.
        /// </summary>
        internal static string ArgentinianFood {
            get {
                return ResourceManager.GetString("ArgentinianFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Barbecue.
        /// </summary>
        internal static string BrazilianBarbecue {
            get {
                return ResourceManager.GetString("BrazilianBarbecue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Food.
        /// </summary>
        internal static string BrazilianFood {
            get {
                return ResourceManager.GetString("BrazilianFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajun Food.
        /// </summary>
        internal static string CajunFood {
            get {
                return ResourceManager.GetString("CajunFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Cuisine.
        /// </summary>
        internal static string CanadianCuisine {
            get {
                return ResourceManager.GetString("CanadianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribbean Food.
        /// </summary>
        internal static string CaribbeanFood {
            get {
                return ResourceManager.GetString("CaribbeanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Food.
        /// </summary>
        internal static string ChineseFood {
            get {
                return ResourceManager.GetString("ChineseFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuban Food.
        /// </summary>
        internal static string CubanFood {
            get {
                return ResourceManager.GetString("CubanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino Cuisine.
        /// </summary>
        internal static string FilipinoCuisine {
            get {
                return ResourceManager.GetString("FilipinoCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Food.
        /// </summary>
        internal static string FrenchFood {
            get {
                return ResourceManager.GetString("FrenchFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Food.
        /// </summary>
        internal static string GermanFood {
            get {
                return ResourceManager.GetString("GermanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek Food.
        /// </summary>
        internal static string GreekFood {
            get {
                return ResourceManager.GetString("GreekFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Cuisine.
        /// </summary>
        internal static string IndianCuisine {
            get {
                return ResourceManager.GetString("IndianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian Cuisine.
        /// </summary>
        internal static string IndonesianCuisine {
            get {
                return ResourceManager.GetString("IndonesianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iranian Cuisine.
        /// </summary>
        internal static string IranianCuisine {
            get {
                return ResourceManager.GetString("IranianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish Food.
        /// </summary>
        internal static string IrishFood {
            get {
                return ResourceManager.GetString("IrishFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian Food.
        /// </summary>
        internal static string ItalianFood {
            get {
                return ResourceManager.GetString("ItalianFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican Food.
        /// </summary>
        internal static string JamaicanFood {
            get {
                return ResourceManager.GetString("JamaicanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Cuisine.
        /// </summary>
        internal static string JapaneseCuisine {
            get {
                return ResourceManager.GetString("JapaneseCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewish Cuisine.
        /// </summary>
        internal static string JewishCuisine {
            get {
                return ResourceManager.GetString("JewishCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk Food.
        /// </summary>
        internal static string JunkFood {
            get {
                return ResourceManager.GetString("JunkFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Barbecue.
        /// </summary>
        internal static string KoreanBarbecue {
            get {
                return ResourceManager.GetString("KoreanBarbecue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese Food.
        /// </summary>
        internal static string LebaneseFood {
            get {
                return ResourceManager.GetString("LebaneseFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Food.
        /// </summary>
        internal static string MalaysianFood {
            get {
                return ResourceManager.GetString("MalaysianFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean Food.
        /// </summary>
        internal static string MediterraneanFood {
            get {
                return ResourceManager.GetString("MediterraneanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Food.
        /// </summary>
        internal static string MexicanFood {
            get {
                return ResourceManager.GetString("MexicanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Eastern Food.
        /// </summary>
        internal static string MiddleEasternFood {
            get {
                return ResourceManager.GetString("MiddleEasternFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midwestern Food.
        /// </summary>
        internal static string MidwesternFood {
            get {
                return ResourceManager.GetString("MidwesternFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroccan Food.
        /// </summary>
        internal static string MoroccanFood {
            get {
                return ResourceManager.GetString("MoroccanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese Food.
        /// </summary>
        internal static string PortugueseFood {
            get {
                return ResourceManager.GetString("PortugueseFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafood.
        /// </summary>
        internal static string Seafood {
            get {
                return ResourceManager.GetString("Seafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shanghainese Cuisine.
        /// </summary>
        internal static string ShanghaineseCuisine {
            get {
                return ResourceManager.GetString("ShanghaineseCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichuan Cuisine.
        /// </summary>
        internal static string SichuanCuisine {
            get {
                return ResourceManager.GetString("SichuanCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicilian Cuisine.
        /// </summary>
        internal static string SicilianCuisine {
            get {
                return ResourceManager.GetString("SicilianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singaporean Food.
        /// </summary>
        internal static string SingaporeanFood {
            get {
                return ResourceManager.GetString("SingaporeanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Food.
        /// </summary>
        internal static string SoulFood {
            get {
                return ResourceManager.GetString("SoulFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern American Food.
        /// </summary>
        internal static string SouthernAmericanFood {
            get {
                return ResourceManager.GetString("SouthernAmericanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Indian Cuisine.
        /// </summary>
        internal static string SouthIndianCuisine {
            get {
                return ResourceManager.GetString("SouthIndianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korean Food.
        /// </summary>
        internal static string SouthKoreanFood {
            get {
                return ResourceManager.GetString("SouthKoreanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Cuisine.
        /// </summary>
        internal static string SpanishCuisine {
            get {
                return ResourceManager.GetString("SpanishCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Cuisine.
        /// </summary>
        internal static string SwissCuisine {
            get {
                return ResourceManager.GetString("SwissCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas Barbecue.
        /// </summary>
        internal static string TexasBarbecue {
            get {
                return ResourceManager.GetString("TexasBarbecue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tex-Mex Food.
        /// </summary>
        internal static string TexMexFood {
            get {
                return ResourceManager.GetString("TexMexFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai Food.
        /// </summary>
        internal static string ThaiFood {
            get {
                return ResourceManager.GetString("ThaiFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisian Cuisine.
        /// </summary>
        internal static string TunisianCuisine {
            get {
                return ResourceManager.GetString("TunisianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish Food.
        /// </summary>
        internal static string TurkishFood {
            get {
                return ResourceManager.GetString("TurkishFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom Cuisine.
        /// </summary>
        internal static string UnitedKingdomCuisine {
            get {
                return ResourceManager.GetString("UnitedKingdomCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian Food.
        /// </summary>
        internal static string VegetarianFood {
            get {
                return ResourceManager.GetString("VegetarianFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese Food.
        /// </summary>
        internal static string VietnameseFood {
            get {
                return ResourceManager.GetString("VietnameseFood", resourceCulture);
            }
        }
    }
}
