//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenderIdentity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenderIdentity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.GenderIdentity", typeof(GenderIdentity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agender refers to a person who doesn’t identify with any gender identity, often preferring gender-neutral pronouns such as they..
        /// </summary>
        internal static string Agender_Description {
            get {
                return ResourceManager.GetString("Agender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agender.
        /// </summary>
        internal static string Agender_Name {
            get {
                return ResourceManager.GetString("Agender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender expression incorporates both masculine and feminine elements. Androgyne can also describe either gender expression or gender identity..
        /// </summary>
        internal static string Androgyne_Description {
            get {
                return ResourceManager.GetString("Androgyne_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androgyne.
        /// </summary>
        internal static string Androgyne_Name {
            get {
                return ResourceManager.GetString("Androgyne_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who identifies with both female and male genders. A bigender person may express two genders simultaneously or fluctuates between two genders..
        /// </summary>
        internal static string Bigender_Description {
            get {
                return ResourceManager.GetString("Bigender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigender.
        /// </summary>
        internal static string Bigender_Name {
            get {
                return ResourceManager.GetString("Bigender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity matches the gender assigned to them at birth, usually based on their biological sex..
        /// </summary>
        internal static string Cisgender_Description {
            get {
                return ResourceManager.GetString("Cisgender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisgender.
        /// </summary>
        internal static string Cisgender_Name {
            get {
                return ResourceManager.GetString("Cisgender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity is not fixed and changes over time. Genderfluid people can identify with different genders at different times or a combination of genders at once..
        /// </summary>
        internal static string Genderfluid_Description {
            get {
                return ResourceManager.GetString("Genderfluid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderfluid.
        /// </summary>
        internal static string Genderfluid_Name {
            get {
                return ResourceManager.GetString("Genderfluid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An umbrella term that describes anyone whose gender expression or identity does not align with traditional societal expectations..
        /// </summary>
        internal static string GenderNonconforming_Description {
            get {
                return ResourceManager.GetString("GenderNonconforming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender-nonconforming.
        /// </summary>
        internal static string GenderNonconforming_Name {
            get {
                return ResourceManager.GetString("GenderNonconforming_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An umbrella term for a person who doesn’t identify with a single gender identity. This term overlaps with non-binary and can also describe anyone who is not cisgender..
        /// </summary>
        internal static string Genderqueer_Description {
            get {
                return ResourceManager.GetString("Genderqueer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderqueer.
        /// </summary>
        internal static string Genderqueer_Name {
            get {
                return ResourceManager.GetString("Genderqueer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity is midway between male and female..
        /// </summary>
        internal static string Intergender_Description {
            get {
                return ResourceManager.GetString("Intergender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intergender.
        /// </summary>
        internal static string Intergender_Name {
            get {
                return ResourceManager.GetString("Intergender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person born with ambiguously gendered bodies due to chromosome anomalies or ambiguous genitalia. Intersex people often receive a gender assignment at birth through medical intervention, which may or may not correspond to the gender they identify with as they age..
        /// </summary>
        internal static string Intersex_Description {
            get {
                return ResourceManager.GetString("Intersex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersex.
        /// </summary>
        internal static string Intersex_Name {
            get {
                return ResourceManager.GetString("Intersex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who doesn’t fall under the traditional male-female binary. A non-binary person may identify as both male and female, or neither..
        /// </summary>
        internal static string NonBinary_Description {
            get {
                return ResourceManager.GetString("NonBinary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-binary.
        /// </summary>
        internal static string NonBinary_Name {
            get {
                return ResourceManager.GetString("NonBinary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who identifies as a mixture of several genders or as all genders simultaneously, including ones outside the traditional male-female binary. Pangender is another term for omnigender..
        /// </summary>
        internal static string Omnigender_Description {
            get {
                return ResourceManager.GetString("Omnigender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnigender.
        /// </summary>
        internal static string Omnigender_Name {
            get {
                return ResourceManager.GetString("Omnigender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who is in the process of exploration or discovery regarding their gender expression or identity..
        /// </summary>
        internal static string Questioning_Description {
            get {
                return ResourceManager.GetString("Questioning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questioning.
        /// </summary>
        internal static string Questioning_Name {
            get {
                return ResourceManager.GetString("Questioning_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity doesn’t match their assigned sex at birth (often shortened to “trans” or listed with their affirmed gender, e.g., “trans woman” or “trans man”). Some transgender people choose to undergo hormonal treatments or surgeries to match their gender identity, but others do not..
        /// </summary>
        internal static string Transgender_Description {
            get {
                return ResourceManager.GetString("Transgender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transgender.
        /// </summary>
        internal static string Transgender_Name {
            get {
                return ResourceManager.GetString("Transgender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An older term sometimes used to describe a person who has chosen to undergo hormonal treatments or anatomical surgeries to match their gender identity. While some people identify with this term, others find it offensive or outdated because of how the medical community historically used the label..
        /// </summary>
        internal static string Transsexual_Description {
            get {
                return ResourceManager.GetString("Transsexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transsexual.
        /// </summary>
        internal static string Transsexual_Name {
            get {
                return ResourceManager.GetString("Transsexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A broad term that some Indigenous North Americans use to describe people in their community who identify as having both a masculine and feminine spirit. Two-spirit can describe gender expression and/or sexual identity..
        /// </summary>
        internal static string TwoSpirit_Description {
            get {
                return ResourceManager.GetString("TwoSpirit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-spirit.
        /// </summary>
        internal static string TwoSpirit_Name {
            get {
                return ResourceManager.GetString("TwoSpirit_Name", resourceCulture);
            }
        }
    }
}
