//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Intentions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Intentions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Intentions", typeof(Intentions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a more relaxed form of dating. It’s when you’re talking to a person, dating them, or engaging in casual sex, but you are not serious and there is no commitment. Someone who is casually dating someone may also be seeing other people..
        /// </summary>
        internal static string Casual_Description {
            get {
                return ResourceManager.GetString("Casual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term.
        /// </summary>
        internal static string Casual_Group {
            get {
                return ResourceManager.GetString("Casual_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Relationship.
        /// </summary>
        internal static string Casual_Name {
            get {
                return ResourceManager.GetString("Casual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For those who intend to marry (bond established between two people, through governmental, cultural, religious or social recognition) or live together in a short/medium period of time..
        /// </summary>
        internal static string Married_Description {
            get {
                return ResourceManager.GetString("Married_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term.
        /// </summary>
        internal static string Married_Group {
            get {
                return ResourceManager.GetString("Married_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live together / Get Married.
        /// </summary>
        internal static string Married_Name {
            get {
                return ResourceManager.GetString("Married_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious dating is when you’re committed to a person. You have feelings for them, and they have feelings for you. Because of this, you’re not seeing anyone else and you hope to one day take the relationship to the next level..
        /// </summary>
        internal static string Serious_Description {
            get {
                return ResourceManager.GetString("Serious_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term.
        /// </summary>
        internal static string Serious_Group {
            get {
                return ResourceManager.GetString("Serious_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious Relationship.
        /// </summary>
        internal static string Serious_Name {
            get {
                return ResourceManager.GetString("Serious_Name", resourceCulture);
            }
        }
    }
}
