//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeisureActivities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeisureActivities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.LeisureActivities", typeof(LeisureActivities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon Tea.
        /// </summary>
        internal static string AfternoonTea {
            get {
                return ResourceManager.GetString("AfternoonTea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquariums.
        /// </summary>
        internal static string Aquariums {
            get {
                return ResourceManager.GetString("Aquariums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomy.
        /// </summary>
        internal static string Astronomy {
            get {
                return ResourceManager.GetString("Astronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beekeeping.
        /// </summary>
        internal static string Beekeeping {
            get {
                return ResourceManager.GetString("Beekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycling.
        /// </summary>
        internal static string Bicycling {
            get {
                return ResourceManager.GetString("Bicycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdwatching.
        /// </summary>
        internal static string Birdwatching {
            get {
                return ResourceManager.GetString("Birdwatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai.
        /// </summary>
        internal static string Bonsai {
            get {
                return ResourceManager.GetString("Bonsai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowling.
        /// </summary>
        internal static string Bowling {
            get {
                return ResourceManager.GetString("Bowling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calligraphy.
        /// </summary>
        internal static string Calligraphy {
            get {
                return ResourceManager.GetString("Calligraphy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        internal static string Camping {
            get {
                return ResourceManager.GetString("Camping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canoeing.
        /// </summary>
        internal static string Canoeing {
            get {
                return ResourceManager.GetString("Canoeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string Chess {
            get {
                return ResourceManager.GetString("Chess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        internal static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Computing.
        /// </summary>
        internal static string CodingComputing {
            get {
                return ResourceManager.GetString("CodingComputing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting (e.g. Coin Collecting).
        /// </summary>
        internal static string Collecting {
            get {
                return ResourceManager.GetString("Collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerts.
        /// </summary>
        internal static string Concerts {
            get {
                return ResourceManager.GetString("Concerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        internal static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking / Baking.
        /// </summary>
        internal static string CookingBaking {
            get {
                return ResourceManager.GetString("CookingBaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosplaying.
        /// </summary>
        internal static string Cosplaying {
            get {
                return ResourceManager.GetString("Cosplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts.
        /// </summary>
        internal static string Crafts {
            get {
                return ResourceManager.GetString("Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Writing.
        /// </summary>
        internal static string CreativeWriting {
            get {
                return ResourceManager.GetString("CreativeWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Activities.
        /// </summary>
        internal static string CulturalActivities {
            get {
                return ResourceManager.GetString("CulturalActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing.
        /// </summary>
        internal static string Dancing {
            get {
                return ResourceManager.GetString("Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debate.
        /// </summary>
        internal static string Debate {
            get {
                return ResourceManager.GetString("Debate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Out.
        /// </summary>
        internal static string DiningOut {
            get {
                return ResourceManager.GetString("DiningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIY (Do It Yourself).
        /// </summary>
        internal static string DoItYourself {
            get {
                return ResourceManager.GetString("DoItYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Drama {
            get {
                return ResourceManager.GetString("Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing / Painting.
        /// </summary>
        internal static string DrawingPainting {
            get {
                return ResourceManager.GetString("DrawingPainting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving.
        /// </summary>
        internal static string Driving {
            get {
                return ResourceManager.GetString("Driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercising.
        /// </summary>
        internal static string Exercising {
            get {
                return ResourceManager.GetString("Exercising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Design.
        /// </summary>
        internal static string FashionDesign {
            get {
                return ResourceManager.GetString("FashionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivals.
        /// </summary>
        internal static string Festivals {
            get {
                return ResourceManager.GetString("Festivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmmaking.
        /// </summary>
        internal static string Filmmaking {
            get {
                return ResourceManager.GetString("Filmmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games (e.g. Cards, Board, Puzzles).
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardening.
        /// </summary>
        internal static string Gardening {
            get {
                return ResourceManager.GetString("Gardening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymnastics.
        /// </summary>
        internal static string Gymnastics {
            get {
                return ResourceManager.GetString("Gymnastics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        internal static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Improvement.
        /// </summary>
        internal static string HomeImprovement {
            get {
                return ResourceManager.GetString("HomeImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Skating.
        /// </summary>
        internal static string IceSkating {
            get {
                return ResourceManager.GetString("IceSkating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging.
        /// </summary>
        internal static string Jogging {
            get {
                return ResourceManager.GetString("Jogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karaoke.
        /// </summary>
        internal static string Karaoke {
            get {
                return ResourceManager.GetString("Karaoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knitting / Sewing / Patchworking.
        /// </summary>
        internal static string KnittingSewingPatchworking {
            get {
                return ResourceManager.GetString("KnittingSewingPatchworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning (e.g. Languages).
        /// </summary>
        internal static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Arts.
        /// </summary>
        internal static string MartialArts {
            get {
                return ResourceManager.GetString("MartialArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditation.
        /// </summary>
        internal static string Meditation {
            get {
                return ResourceManager.GetString("Meditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetalWorking / WoodWorking.
        /// </summary>
        internal static string MetalWorkingWoodWorking {
            get {
                return ResourceManager.GetString("MetalWorkingWoodWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Building.
        /// </summary>
        internal static string ModelBuilding {
            get {
                return ResourceManager.GetString("ModelBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museums.
        /// </summary>
        internal static string Museums {
            get {
                return ResourceManager.GetString("Museums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks / Zoos.
        /// </summary>
        internal static string ParksZoos {
            get {
                return ResourceManager.GetString("ParksZoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Reflection.
        /// </summary>
        internal static string PersonalReflection {
            get {
                return ResourceManager.GetString("PersonalReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        internal static string Photography {
            get {
                return ResourceManager.GetString("Photography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picnics.
        /// </summary>
        internal static string Picnics {
            get {
                return ResourceManager.GetString("Picnics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotics.
        /// </summary>
        internal static string Robotics {
            get {
                return ResourceManager.GetString("Robotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollerblading.
        /// </summary>
        internal static string Rollerblading {
            get {
                return ResourceManager.GetString("Rollerblading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailing &amp; Boating.
        /// </summary>
        internal static string SailingBoating {
            get {
                return ResourceManager.GetString("SailingBoating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightseeing.
        /// </summary>
        internal static string Sightseeing {
            get {
                return ResourceManager.GetString("Sightseeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singing.
        /// </summary>
        internal static string Singing {
            get {
                return ResourceManager.GetString("Singing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiing &amp; Snowboarding.
        /// </summary>
        internal static string SkiingSnowboarding {
            get {
                return ResourceManager.GetString("SkiingSnowboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snorkeling &amp; Diving.
        /// </summary>
        internal static string SnorkelingDiving {
            get {
                return ResourceManager.GetString("SnorkelingDiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunbathing.
        /// </summary>
        internal static string Sunbathing {
            get {
                return ResourceManager.GetString("Sunbathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfing.
        /// </summary>
        internal static string Surfing {
            get {
                return ResourceManager.GetString("Surfing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming.
        /// </summary>
        internal static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Sports.
        /// </summary>
        internal static string TeamSports {
            get {
                return ResourceManager.GetString("TeamSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television.
        /// </summary>
        internal static string Television {
            get {
                return ResourceManager.GetString("Television", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theatre.
        /// </summary>
        internal static string Theatre {
            get {
                return ResourceManager.GetString("Theatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Parks.
        /// </summary>
        internal static string ThemeParks {
            get {
                return ResourceManager.GetString("ThemeParks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        internal static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Games.
        /// </summary>
        internal static string VideoGames {
            get {
                return ResourceManager.GetString("VideoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Production.
        /// </summary>
        internal static string VideoProduction {
            get {
                return ResourceManager.GetString("VideoProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        internal static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightlifting.
        /// </summary>
        internal static string Weightlifting {
            get {
                return ResourceManager.GetString("Weightlifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoga.
        /// </summary>
        internal static string Yoga {
            get {
                return ResourceManager.GetString("Yoga", resourceCulture);
            }
        }
    }
}
