//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoveLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoveLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.LoveLanguage", typeof(LoveLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This love language expresses itself by doing things that you know your spouse would like. Cooking a meal, doing laundry, and picking up a recipe are all acts of service. They require some thought, time and effort..
        /// </summary>
        internal static string ActsOfServices_Description {
            get {
                return ResourceManager.GetString("ActsOfServices_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acts Of Services.
        /// </summary>
        internal static string ActsOfServices_Name {
            get {
                return ResourceManager.GetString("ActsOfServices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For people with this love language, nothing is more impactful than their partner&apos;s physical touch. They don&apos;t like over-the-top DPA (Public Display of Affection), but they feel more connected and secure in a relationship, holding hands, kissing, hugging, etc..
        /// </summary>
        internal static string PhysicalTouch_Description {
            get {
                return ResourceManager.GetString("PhysicalTouch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Touch.
        /// </summary>
        internal static string PhysicalTouch_Name {
            get {
                return ResourceManager.GetString("PhysicalTouch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This love language is all about exclusive attention. No televisions, no smartphones or any other distractions. If this is your partner&apos;s primary language, they don&apos;t just want to be included during this time, they want to be the center of your attention. They want their partners to look at them and only them..
        /// </summary>
        internal static string QualityTime_Description {
            get {
                return ResourceManager.GetString("QualityTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Time.
        /// </summary>
        internal static string QualityTime_Name {
            get {
                return ResourceManager.GetString("QualityTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This love language is not necessarily materialistic. It just means that a meaningful or thoughtful gift makes your partner feel loved and appreciated. Something as simple as grabbing a pint of your favorite ice cream after a long week at work can have a big impact..
        /// </summary>
        internal static string ReceivingGifts_Description {
            get {
                return ResourceManager.GetString("ReceivingGifts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Gifts.
        /// </summary>
        internal static string ReceivingGifts_Name {
            get {
                return ResourceManager.GetString("ReceivingGifts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This love language expresses love with words that edify your partner. Verbal praise doesn&apos;t have to be complicated; the shortest, simplest compliments can be the most effective..
        /// </summary>
        internal static string WordsOfAffirmation_Description {
            get {
                return ResourceManager.GetString("WordsOfAffirmation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Of Affirmation.
        /// </summary>
        internal static string WordsOfAffirmation_Name {
            get {
                return ResourceManager.GetString("WordsOfAffirmation_Name", resourceCulture);
            }
        }
    }
}
