//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoneyPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoneyPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.MoneyPersonality", typeof(MoneyPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why settle for the ordinary when you can buy yourself the extraordinary?.
        /// </summary>
        internal static string Celebrity_Description {
            get {
                return ResourceManager.GetString("Celebrity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrity.
        /// </summary>
        internal static string Celebrity_Name {
            get {
                return ResourceManager.GetString("Celebrity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making money comes naturally to you because work is the love of your life..
        /// </summary>
        internal static string Conqueror_Description {
            get {
                return ResourceManager.GetString("Conqueror_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conqueror.
        /// </summary>
        internal static string Conqueror_Name {
            get {
                return ResourceManager.GetString("Conqueror_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know how to enjoy life. Money’s not going to get in the way of your freedom!.
        /// </summary>
        internal static string Hedonist_Description {
            get {
                return ResourceManager.GetString("Hedonist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedonist.
        /// </summary>
        internal static string Hedonist_Name {
            get {
                return ResourceManager.GetString("Hedonist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re aware that money is a necessary part of life, but you&apos;d rather not get bogged down with it..
        /// </summary>
        internal static string Idealist_Description {
            get {
                return ResourceManager.GetString("Idealist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idealist.
        /// </summary>
        internal static string Idealist_Name {
            get {
                return ResourceManager.GetString("Idealist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your savings provide for the people you love if they ever find themselves in a pinch..
        /// </summary>
        internal static string Nurturer_Description {
            get {
                return ResourceManager.GetString("Nurturer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurturer.
        /// </summary>
        internal static string Nurturer_Name {
            get {
                return ResourceManager.GetString("Nurturer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re always saving for a rainy day, just in case..
        /// </summary>
        internal static string Stockpiler_Description {
            get {
                return ResourceManager.GetString("Stockpiler_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stockpiler.
        /// </summary>
        internal static string Stockpiler_Name {
            get {
                return ResourceManager.GetString("Stockpiler_Name", resourceCulture);
            }
        }
    }
}
