//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.MovieGenre", typeof(MovieGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action genre films are defined by risk and challenge. Including fight scenes, stunts, car chases and general danger. (Heroic Bloodshed, Military Action, Espionage, Wuxia, Disaster, Adventure, Superhero).
        /// </summary>
        internal static string Action_Description {
            get {
                return ResourceManager.GetString("Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action_Name {
            get {
                return ResourceManager.GetString("Action_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The genre of animation is defined by inanimate objects being manipulated to appear alive. (Traditional, Stop Motion, Claymation, Cutout, Computer Generated Images - CGI, Puppetry, Live-Action).
        /// </summary>
        internal static string Animation_Description {
            get {
                return ResourceManager.GetString("Animation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Animation_Name {
            get {
                return ResourceManager.GetString("Animation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comedy genre is defined by events that are intended to make someone laugh, whether the story is macabre, funny or silly. (Action Comedy, Dark Comedy, Romantic Comedy, Buddy Comedy, Road Comedy, Slap Comedy, Parody, Satire, Sitcom, Sketch Comedy, Mockumentary, prank).
        /// </summary>
        internal static string Comedy_Description {
            get {
                return ResourceManager.GetString("Comedy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string Comedy_Name {
            get {
                return ResourceManager.GetString("Comedy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crime genre deals with both sides of the criminal justice system, but does not focus on legislative issues or civil cases and lawsuits. (Caper, Heist, Gangster, Policeman, Detective, Court, Procedural).
        /// </summary>
        internal static string Crime_Description {
            get {
                return ResourceManager.GetString("Crime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        internal static string Crime_Name {
            get {
                return ResourceManager.GetString("Crime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dramatic genre is defined by conflict and often looks to reality rather than sensationalism. (Melodrama, Teen Drama, Philosophical Drama, Medical Drama, Legal Drama, Political Drama, Anthropological Drama, Religious Drama, Docudrama).
        /// </summary>
        internal static string Drama_Description {
            get {
                return ResourceManager.GetString("Drama_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Drama_Name {
            get {
                return ResourceManager.GetString("Drama_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experimental genre is often defined by the idea that the work of art and entertainment does not fit into a particular genre or subgenre, and is conceived as such. (Surrealistic, Absurd).
        /// </summary>
        internal static string Experimental_Description {
            get {
                return ResourceManager.GetString("Experimental_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        internal static string Experimental_Name {
            get {
                return ResourceManager.GetString("Experimental_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fantasy genre is defined by both the circumstances and the setting within a fictional universe with an unrealistic set of natural laws. (Contemporary Fantasy, Urban Fantasy, Dark Fantasy, Elevated Fantasy, Myth).
        /// </summary>
        internal static string Fantasy_Description {
            get {
                return ResourceManager.GetString("Fantasy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string Fantasy_Name {
            get {
                return ResourceManager.GetString("Fantasy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The historical genre can be divided into two sections. One deals with accurate representations of historical accounts, which may include biographies, autobiographies, and memoirs. The other section is made up of fictional films that are placed within an accurate representation of a historical setting. (Historical event, biography, historical epic, historical fiction, period piece, alternative history).
        /// </summary>
        internal static string Historical_Description {
            get {
                return ResourceManager.GetString("Historical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical.
        /// </summary>
        internal static string Historical_Name {
            get {
                return ResourceManager.GetString("Historical_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horror genre is centered around the depiction of terrifying or macabre events for the sake of entertainment. (Ghost, Monster, Werewolf, Vampire, Hidden, Slasher, Splatter, Found footage, Zombie).
        /// </summary>
        internal static string Horror_Description {
            get {
                return ResourceManager.GetString("Horror_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string Horror_Name {
            get {
                return ResourceManager.GetString("Horror_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musicals can incorporate any other genre, but they do incorporate characters who sing songs and perform dance numbers..
        /// </summary>
        internal static string Musical_Description {
            get {
                return ResourceManager.GetString("Musical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        internal static string Musical_Name {
            get {
                return ResourceManager.GetString("Musical_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The romance genre is defined by intimate relationships. (romance drama, romance thriller, period romance).
        /// </summary>
        internal static string Romance_Description {
            get {
                return ResourceManager.GetString("Romance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        internal static string Romance_Name {
            get {
                return ResourceManager.GetString("Romance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science fiction films are defined by a mixture of speculation and science. (Post-apocalyptic, Utopian, Dystopian, Cyberpunk, Steampunk, Tech Noir, Space Opera, Contemporary, Military).
        /// </summary>
        internal static string ScienceFiction_Description {
            get {
                return ResourceManager.GetString("ScienceFiction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        internal static string ScienceFiction_Name {
            get {
                return ResourceManager.GetString("ScienceFiction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A thriller story is primarily about emotional purpose, which is to provoke strong emotions, mainly dealing with generating suspense and anxiety. (Psychological, Mystery, Techno, Film Noir).
        /// </summary>
        internal static string Thriller_Description {
            get {
                return ResourceManager.GetString("Thriller_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        internal static string Thriller_Name {
            get {
                return ResourceManager.GetString("Thriller_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War movies revolve around large-scale conflicts between opposing forces within a universe that shares the same natural laws as our own..
        /// </summary>
        internal static string War_Description {
            get {
                return ResourceManager.GetString("War_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        internal static string War_Name {
            get {
                return ResourceManager.GetString("War_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westerns are defined by their setting and time period. The story needs to be set in the American West, which begins at the eastern end of Missouri and extends to the Pacific Ocean. (Epic Western, Empire Western, Marshal Western, Outlaw Western, Revenge Western, Revisionist Western, Spaghetti Western).
        /// </summary>
        internal static string Western_Description {
            get {
                return ResourceManager.GetString("Western_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        internal static string Western_Name {
            get {
                return ResourceManager.GetString("Western_Name", resourceCulture);
            }
        }
    }
}
