//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyersBriggsTypeIndicator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyersBriggsTypeIndicator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.MyersBriggsTypeIndicator", typeof(MyersBriggsTypeIndicator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who share the Protagonist personality type feel more at home when they are in a relationship, and few types are more eager to make a romantic commitment to their chosen partner. The protagonists take dating and relationships seriously, selecting partners with a long-term view rather than the more casual approach you might expect from some Explorer types. There is no greater joy for the Protagonists than helping towards the goals of someone they care about, and the intertwining of lives that a committ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENFJ_Description {
            get {
                return ResourceManager.GetString("ENFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        internal static string ENFJ_Group {
            get {
                return ResourceManager.GetString("ENFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonist (ENFJ).
        /// </summary>
        internal static string ENFJ_Name {
            get {
                return ResourceManager.GetString("ENFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to relationships, there&apos;s hardly anyone around who&apos;s more excited than Campaigners to share with their partners the abundance of insightful insights and experiences life has to offer. For people with the Campaigners personality type, relationships are a joyful process of mutual exploration and imagination, a chance to connect with another soul. Campaigners take their relationships seriously and are known for their uninhibited and unwavering devotion to the people to whom they have committed th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENFP_Description {
            get {
                return ResourceManager.GetString("ENFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        internal static string ENFP_Group {
            get {
                return ResourceManager.GetString("ENFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigner (ENFP).
        /// </summary>
        internal static string ENFP_Name {
            get {
                return ResourceManager.GetString("ENFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As in other areas of their lives, commanders approach dating and relationships with a set of goals and a plan to achieve them, and they do so with impressive energy and enthusiasm. People with the Commander personality type want to win and will gladly take on leadership roles in relationships early on, taking personal responsibility for how things go and actively working to ensure a mutually rewarding experience. Romantic relationships are serious business, and commanders have been at it for a long time. (C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENTJ_Description {
            get {
                return ResourceManager.GetString("ENTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        internal static string ENTJ_Group {
            get {
                return ResourceManager.GetString("ENTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander (ENTJ).
        /// </summary>
        internal static string ENTJ_Name {
            get {
                return ResourceManager.GetString("ENTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there&apos;s one thing Debaters are good at, it&apos;s coming up with a never-ending stream of innovations and ideas to keep things moving forward, and that&apos;s evident in their romantic relationships as well. For people with the Breakthrough personality type, growth is key, and even before they find a dating partner, they imagine all the ways they can try new things together, to grow together. This can be an overwhelming process if your partner doesn&apos;t respond, but when Innovators find someone who shares their love [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENTP_Description {
            get {
                return ResourceManager.GetString("ENTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        internal static string ENTP_Group {
            get {
                return ResourceManager.GetString("ENTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debater (ENTP).
        /// </summary>
        internal static string ENTP_Name {
            get {
                return ResourceManager.GetString("ENTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuing social validation and a sense of belonging so highly, romantic relationships hold a special level of importance for consuls. No other relationship type provides people with the Consul personality type the same level of support and devotion, and the feelings of security and stability that accompany strong romantic relationships are extremely warm. (Combine with ISFP and ISTP).
        /// </summary>
        internal static string ESFJ_Description {
            get {
                return ResourceManager.GetString("ESFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        internal static string ESFJ_Group {
            get {
                return ResourceManager.GetString("ESFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consul (ESFJ).
        /// </summary>
        internal static string ESFJ_Name {
            get {
                return ResourceManager.GetString("ESFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainers are sociable, fun-loving and free-spirited people who live life in the moment and extract every bit of emotion from everything. Naturally, they spare none of that freshness and energy in dating. For people with the Entertainer personality type, relationships aren&apos;t about slowly building the groundwork for the future or planning a life - they&apos;re bubbly, unpredictable things to enjoy as long as there&apos;s pleasure to be had. (Combine with ISTJ and ISFJ).
        /// </summary>
        internal static string ESFP_Description {
            get {
                return ResourceManager.GetString("ESFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string ESFP_Group {
            get {
                return ResourceManager.GetString("ESFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainer (ESFP).
        /// </summary>
        internal static string ESFP_Name {
            get {
                return ResourceManager.GetString("ESFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executives are quite unique in the sense that their relationships don&apos;t really change as they progress from the dating phase to more stable, long-term relationships and even further into marriage. Because they value honesty and openness so much, people with an executive personality tend to be clear about who they are, what they are like, and what their goals are from the start, and they should follow through on these statements for the long haul. As long as your partner is able to take your word for it and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESTJ_Description {
            get {
                return ResourceManager.GetString("ESTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        internal static string ESTJ_Group {
            get {
                return ResourceManager.GetString("ESTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive (ESTJ).
        /// </summary>
        internal static string ESTJ_Name {
            get {
                return ResourceManager.GetString("ESTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to romantic relationships, it can hardly be said that people with the Enterprising personality type are missing their wedding day. Life is fun and full of surprises (something entrepreneurs have a knack for delivering), and they enjoy everything here and now. Entrepreneurs may not spend a lot of time planning “someday,” but their enthusiasm and unpredictability make them exciting dating partners. (Combine with ISTJ and ISFJ).
        /// </summary>
        internal static string ESTP_Description {
            get {
                return ResourceManager.GetString("ESTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string ESTP_Group {
            get {
                return ResourceManager.GetString("ESTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneur (ESTP).
        /// </summary>
        internal static string ESTP_Name {
            get {
                return ResourceManager.GetString("ESTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advocates (INFJs) tend to take the process of finding a romantic partner seriously. People with this personality type seek depth and meaning in their relationships, preferring not to settle for a union that is based on anything less than true love. It can take some time for Advocates to find a compatible partner. Some people may think Advocates are too demanding and it&apos;s true that these personalities can have unrealistic expectations. Some Advocates may expect a &apos;perfect&apos; partner or relationship that ultima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INFJ_Description {
            get {
                return ResourceManager.GetString("INFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        internal static string INFJ_Group {
            get {
                return ResourceManager.GetString("INFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advocate (INFJ).
        /// </summary>
        internal static string INFJ_Name {
            get {
                return ResourceManager.GetString("INFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediators (INFPs) are dreamers and idealists, especially when it comes to romance. The concept of true love resonates with them, and they are unlikely to be happy in a relationship based on anything less. People with this personality type may daydream about the perfect relationship, imagining what it would be like to share their innermost self with another person. (Combine with ENFJ and ENTJ).
        /// </summary>
        internal static string INFP_Description {
            get {
                return ResourceManager.GetString("INFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        internal static string INFP_Group {
            get {
                return ResourceManager.GetString("INFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediator (INFP).
        /// </summary>
        internal static string INFP_Name {
            get {
                return ResourceManager.GetString("INFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architects (INTJs) approach romance the way they do most challenges: strategically, with clear-cut goals and a plan for achieving them. In a purely rational world, this approach would be foolproof. Alas, love is rarely rational, and Architects are at risk of overlooking or misinterpreting the unpredictability of human nature and affection. (Combine with ENTP and ENFP).
        /// </summary>
        internal static string INTJ_Description {
            get {
                return ResourceManager.GetString("INTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        internal static string INTJ_Group {
            get {
                return ResourceManager.GetString("INTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect (INTJ).
        /// </summary>
        internal static string INTJ_Name {
            get {
                return ResourceManager.GetString("INTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to romantic relationships, logicians have an interesting mix of traits that often pleasantly surprise their partners. People with this personality type are always full of ideas, but have little opportunity to explore their more romantic notions. As with any of their theories, logicians love to share with others, and when they finally meet someone where romantic thoughts are appropriate, they are excited, enthusiastic, and even playful, flirting with wordplay and intellectual play. (Combine wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INTP_Description {
            get {
                return ResourceManager.GetString("INTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        internal static string INTP_Group {
            get {
                return ResourceManager.GetString("INTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logician (INTP).
        /// </summary>
        internal static string INTP_Name {
            get {
                return ResourceManager.GetString("INTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to romantic relationships, the kindness of the Defenders turns into a joy that is only found in taking care of your family and home, in being there for emotional and practical support whenever needed. Home is where the heart is for people with the Defender personality type, and in no other area of their lives do they strive so hard to create the harmony and beauty they want to see in the world. (Combine with ESFP and ESTP).
        /// </summary>
        internal static string ISFJ_Description {
            get {
                return ResourceManager.GetString("ISFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        internal static string ISFJ_Group {
            get {
                return ResourceManager.GetString("ISFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender (ISFJ).
        /// </summary>
        internal static string ISFJ_Name {
            get {
                return ResourceManager.GetString("ISFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurers are quite mysterious and hard to get to know. Although they are very emotional individuals, they guard this sensitive core carefully, preferring to listen rather than express. People with the Adventurer personality type focus on their partners, with little interest in dictating the mood of a situation with their own feelings. While this can sometimes be frustrating, if they are accepted for what they are, Adventurers prove to be warm and enthusiastic partners. (Combine with ESTJ and ESFJ).
        /// </summary>
        internal static string ISFP_Description {
            get {
                return ResourceManager.GetString("ISFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string ISFP_Group {
            get {
                return ResourceManager.GetString("ISFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurer (ISFP).
        /// </summary>
        internal static string ISFP_Name {
            get {
                return ResourceManager.GetString("ISFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logisticians are totally trustworthy and this trait is clearly expressed when it comes to their romantic relationships. Often representing the epitome of family values, people with the Logistics personality type are comfortable with, and often even encourage, traditional domestic and gender roles, and look for a family structure guided by clear expectations and honesty. While their reserved nature often makes dating logisticians a challenge, they are truly dedicated partners, willing to put a lot of thought [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISTJ_Description {
            get {
                return ResourceManager.GetString("ISTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        internal static string ISTJ_Group {
            get {
                return ResourceManager.GetString("ISTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistician (ISTJ).
        /// </summary>
        internal static string ISTJ_Name {
            get {
                return ResourceManager.GetString("ISTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to romantic relationships with Virtuosos, it&apos;s a bit like nailing jelly to a tree. Dating personalities Virtuoso is a tango, complex and interesting, with alternating coldness and detachment, and passion, spontaneity and pleasure of the moment. Nothing can be forced in Virtuoso relationships, but as long as they are given the space they need to be themselves, they will be happy to enjoy the comfort of a stable partner for life. (Combine with ESFJ and ESTJ).
        /// </summary>
        internal static string ISTP_Description {
            get {
                return ResourceManager.GetString("ISTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string ISTP_Group {
            get {
                return ResourceManager.GetString("ISTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuoso (ISTP).
        /// </summary>
        internal static string ISTP_Name {
            get {
                return ResourceManager.GetString("ISTP_Name", resourceCulture);
            }
        }
    }
}
