//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RaceCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RaceCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.RaceCategory", typeof(RaceCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person having origins in any of the original peoples of North and South America (including Central America) and who maintains tribal affiliation or community attachment..
        /// </summary>
        internal static string AmericanIndianAlaskaNative_Description {
            get {
                return ResourceManager.GetString("AmericanIndianAlaskaNative_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Indian and Alaska Native.
        /// </summary>
        internal static string AmericanIndianAlaskaNative_Name {
            get {
                return ResourceManager.GetString("AmericanIndianAlaskaNative_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam..
        /// </summary>
        internal static string Asian_Description {
            get {
                return ResourceManager.GetString("Asian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian.
        /// </summary>
        internal static string Asian_Name {
            get {
                return ResourceManager.GetString("Asian_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person having origins in any of the Black racial groups of Africa..
        /// </summary>
        internal static string BlackAfricanAmerican_Description {
            get {
                return ResourceManager.GetString("BlackAfricanAmerican_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black or African American.
        /// </summary>
        internal static string BlackAfricanAmerican_Name {
            get {
                return ResourceManager.GetString("BlackAfricanAmerican_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands..
        /// </summary>
        internal static string NativeHawaiianOtherPacificIslander_Description {
            get {
                return ResourceManager.GetString("NativeHawaiianOtherPacificIslander_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Hawaiian and Other Pacific Islander.
        /// </summary>
        internal static string NativeHawaiianOtherPacificIslander_Name {
            get {
                return ResourceManager.GetString("NativeHawaiianOtherPacificIslander_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who does not identify by any of the races listed..
        /// </summary>
        internal static string Other_Description {
            get {
                return ResourceManager.GetString("Other_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other_Name {
            get {
                return ResourceManager.GetString("Other_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who can identify by two or more of the races listed..
        /// </summary>
        internal static string TwoMoreRaces_Description {
            get {
                return ResourceManager.GetString("TwoMoreRaces_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more races.
        /// </summary>
        internal static string TwoMoreRaces_Name {
            get {
                return ResourceManager.GetString("TwoMoreRaces_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person having origins in any of the original peoples of Europe, the Middle East, or North Africa..
        /// </summary>
        internal static string White_Description {
            get {
                return ResourceManager.GetString("White_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White_Name {
            get {
                return ResourceManager.GetString("White_Name", resourceCulture);
            }
        }
    }
}
