//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RelationshipPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelationshipPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.RelationshipPersonality", typeof(RelationshipPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These people have family, friends and the union with loved ones as their main value in life. They are serene, sociable and very peaceful people. They avoid getting involved in conflicts and taking risks as much as possible..
        /// </summary>
        internal static string Builders_Description {
            get {
                return ResourceManager.GetString("Builders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builders.
        /// </summary>
        internal static string Builders_Name {
            get {
                return ResourceManager.GetString("Builders_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an analytical personality, people who prioritize logic and common sense above all else. They are very balanced and practical people, who tend to use reason to make their decisions..
        /// </summary>
        internal static string Directors_Description {
            get {
                return ResourceManager.GetString("Directors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        internal static string Directors_Name {
            get {
                return ResourceManager.GetString("Directors_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These people treat love as an adventure. They are impulsive and autonomous, very curious and are always focused on enjoying the moment, maintaining a “let life take me” attitude..
        /// </summary>
        internal static string Explorers_Description {
            get {
                return ResourceManager.GetString("Explorers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string Explorers_Name {
            get {
                return ResourceManager.GetString("Explorers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating people are expressive, empathetic and idealistic. They usually have very sensitive profiles, but they have a lot of imagination and a very open mind. In addition, they need to delve into their feelings and like people to satisfy their emotional needs..
        /// </summary>
        internal static string Negotiator_Description {
            get {
                return ResourceManager.GetString("Negotiator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiator.
        /// </summary>
        internal static string Negotiator_Name {
            get {
                return ResourceManager.GetString("Negotiator_Name", resourceCulture);
            }
        }
    }
}
