//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RelationshipPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelationshipPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.RelationshipPersonality", typeof(RelationshipPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builders are the traditional, loyal, balanced types, powered by serotonin (the calming hormone). These people are very routine-oriented and highly planned, valuing authority, rules, and precision. They are typically grounded and fact-based, conscientious and cautious. Builders want to do a thorough job, and they want to do it right the first time. They revere home and family and have a sense of what they “should” be doing at all times. Builders are often attracted to those like themselves, preferring to sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Builders_Description {
            get {
                return ResourceManager.GetString("Builders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builders.
        /// </summary>
        internal static string Builders_Name {
            get {
                return ResourceManager.GetString("Builders_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors are powered by testosterone. They are analytical and logical, direct and forthcoming. They are sure of themselves, independent, decisive, and skeptical. Directors are resourceful, competitive, and type A, often making excellent leaders. These types tend to be drawn to estrogen-oriented Negotiators, their opposites; the complementary match provides a perfect pairing for the emotionality and people skills that Directors lack..
        /// </summary>
        internal static string Directors_Description {
            get {
                return ResourceManager.GetString("Directors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        internal static string Directors_Name {
            get {
                return ResourceManager.GetString("Directors_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers are the doers, and they&apos;re powered by dopamine (a neurotransmitter involved in pleasure-seeking and motivation). Explorers seek novelty and excitement, and love to learn, travel, and meet new people. They are highly curious, goal-oriented, and value their independence. They live in the moment and typically have a ton of energy. Explorers are often attracted to those who similar-minded. They contend that if you want to do, learn, seek, and experience, you wouldn’t do well with someone who didn’t sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Explorers_Description {
            get {
                return ResourceManager.GetString("Explorers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        internal static string Explorers_Name {
            get {
                return ResourceManager.GetString("Explorers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiators are characterized by estrogen. They&apos;re intuitive, charming, insightful, and caring. They do well with ambiguity, and can read between the lines. Negotiators are highly empathetic, and are skilled at organizing and connecting people. They like when everyone gets along, and they are also emotionally expressive. These types are often drawn to testosterone-led Directors, their opposites; Directors can lend the logic, directness, and decisiveness skills that Negotiators often lack..
        /// </summary>
        internal static string Negotiator_Description {
            get {
                return ResourceManager.GetString("Negotiator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiator.
        /// </summary>
        internal static string Negotiator_Name {
            get {
                return ResourceManager.GetString("Negotiator_Name", resourceCulture);
            }
        }
    }
}
