//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Religion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Religion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Religion", typeof(Religion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generally, these traditions are oral rather than scriptural and passed down from one generation to another through folk tales, songs, and festivals, include belief in an amount of higher and lower gods, sometimes including a supreme creator or force, belief in spirits, veneration of the dead, use of magic and traditional African medicine..
        /// </summary>
        internal static string AfricanTraditionalReligions_Description {
            get {
                return ResourceManager.GetString("AfricanTraditionalReligions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to African Traditional Religions.
        /// </summary>
        internal static string AfricanTraditionalReligions_Name {
            get {
                return ResourceManager.GetString("AfricanTraditionalReligions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-theistic philosophy or religion that originally emerged in India around the 6th century BC. and encompasses diverse traditions, beliefs and practices based on the teachings, the Dharma, of Siddhartha Gautama, entitled Buddha..
        /// </summary>
        internal static string Buddhism_Description {
            get {
                return ResourceManager.GetString("Buddhism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhism.
        /// </summary>
        internal static string Buddhism_Name {
            get {
                return ResourceManager.GetString("Buddhism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese folk religion, also known as Chinese popular religion is a general term covering a range of traditional religious practices of Han Chinese, including the Chinese diaspora..
        /// </summary>
        internal static string ChineseTraditionalReligion_Description {
            get {
                return ResourceManager.GetString("ChineseTraditionalReligion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional Religion.
        /// </summary>
        internal static string ChineseTraditionalReligion_Name {
            get {
                return ResourceManager.GetString("ChineseTraditionalReligion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a monotheistic Abrahamic religion centered on the life and teachings of Jesus of Nazareth as presented in the New Testament. The Christian faith essentially believes in Jesus as the Christ, Son of God, Savior and Lord..
        /// </summary>
        internal static string Christianity_Description {
            get {
                return ResourceManager.GetString("Christianity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christianity.
        /// </summary>
        internal static string Christianity_Name {
            get {
                return ResourceManager.GetString("Christianity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic religion or indigenous religion is a term that may include officially sanctioned civil religions organized with an organized clergy, but which are characterized by the fact that their adherents are often defined by a common ethnicity and conversion essentially amounts to a cultural assimilation for the people in question..
        /// </summary>
        internal static string EthnicReligions_Description {
            get {
                return ResourceManager.GetString("EthnicReligions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic Religions.
        /// </summary>
        internal static string EthnicReligions_Name {
            get {
                return ResourceManager.GetString("EthnicReligions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinduism encompasses Brahmanism, ie the belief in the &apos;Universal Soul&apos;, Brahman; in a more specific sense, the term refers to the caste-ordered cultural and religious world of post-Buddhist India..
        /// </summary>
        internal static string Hinduism_Description {
            get {
                return ResourceManager.GetString("Hinduism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinduism.
        /// </summary>
        internal static string Hinduism_Name {
            get {
                return ResourceManager.GetString("Hinduism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a monotheistic Abrahamic religion articulated by the Quran, a text considered by its followers to be the literal word of God, and by the normative teachings and examples of Muhammad, considered by the faithful to be the last prophet of God..
        /// </summary>
        internal static string Islam_Description {
            get {
                return ResourceManager.GetString("Islam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islam.
        /// </summary>
        internal static string Islam_Name {
            get {
                return ResourceManager.GetString("Islam_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judaism is an Abrahamic, monotheistic, and ethnic religion comprising the collective religious, cultural, and legal tradition and civilization of the Jewish people..
        /// </summary>
        internal static string Judaism_Description {
            get {
                return ResourceManager.GetString("Judaism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judaism.
        /// </summary>
        internal static string Judaism_Name {
            get {
                return ResourceManager.GetString("Judaism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irreligion (also referred to as unbelief, absence of religion, or people without religion) is the absence, indifference, or non-practice of a religion. (Agnostics, Atheists, Deists).
        /// </summary>
        internal static string NonReligious_Description {
            get {
                return ResourceManager.GetString("NonReligious_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonreligious / Agnostic / Atheist.
        /// </summary>
        internal static string NonReligious_Name {
            get {
                return ResourceManager.GetString("NonReligious_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May include: Baháʼí, Jainism, Shinto, Cao Dai, Zoroastrianism, Tenrikyo, Animism, Neo-Paganism, Unitarian Universalism, Rastafari, etc..
        /// </summary>
        internal static string Other_Description {
            get {
                return ResourceManager.GetString("Other_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other_Name {
            get {
                return ResourceManager.GetString("Other_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikhism emphasizes simran (ਸਿਮਰਨ, meditation and remembrance of the teachings of Gurus), which can be expressed musically through kirtan, or internally through naam japna (&apos;meditation on His name&apos;) as a means to feel God&apos;s presence. It teaches followers to transform the &apos;Five Thieves&apos; (i.e. lust, rage, greed, attachment, and ego)..
        /// </summary>
        internal static string Sikhism_Description {
            get {
                return ResourceManager.GetString("Sikhism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikhism.
        /// </summary>
        internal static string Sikhism_Name {
            get {
                return ResourceManager.GetString("Sikhism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritist philosophy postulates that humans, along with all other living beings, are essentially immortal spirits that temporarily inhabit physical bodies for several necessary incarnations to attain moral and intellectual improvement..
        /// </summary>
        internal static string Spiritism_Description {
            get {
                return ResourceManager.GetString("Spiritism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritism.
        /// </summary>
        internal static string Spiritism_Name {
            get {
                return ResourceManager.GetString("Spiritism_Name", resourceCulture);
            }
        }
    }
}
