//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SexPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SexPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.SexPersonality", typeof(SexPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one who sees sex as a form of relaxation, an outlet for moments when she feels tense, stressed or upset..
        /// </summary>
        internal static string Decompresser_Description {
            get {
                return ResourceManager.GetString("Decompresser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompresser.
        /// </summary>
        internal static string Decompresser_Name {
            get {
                return ResourceManager.GetString("Decompresser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sex tourist: curious and eager to learn new things. She likes to go beyond her comfort zone and doesn&apos;t take sex too seriously..
        /// </summary>
        internal static string Explorer_Description {
            get {
                return ResourceManager.GetString("Explorer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string Explorer_Name {
            get {
                return ResourceManager.GetString("Explorer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one that gives extreme importance to the give-receive equation, so that it is balanced. He likes to know that both are attentive to each other&apos;s needs and willing to work as a team..
        /// </summary>
        internal static string FairTrader_Description {
            get {
                return ResourceManager.GetString("FairTrader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair Trader.
        /// </summary>
        internal static string FairTrader_Name {
            get {
                return ResourceManager.GetString("FairTrader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one who gives more than receives and is in tune with her partner&apos;s experiences and needs. A person for whom it is important to know that they can make the other person feel good..
        /// </summary>
        internal static string Giver_Description {
            get {
                return ResourceManager.GetString("Giver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giver.
        /// </summary>
        internal static string Giver_Name {
            get {
                return ResourceManager.GetString("Giver_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one that emphasizes safety more than anything. This characteristic is typical of those who have suffered some type of trauma or simply need the bond of trust with their partner in moments of intimacy..
        /// </summary>
        internal static string Guardian_Description {
            get {
                return ResourceManager.GetString("Guardian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        internal static string Guardian_Name {
            get {
                return ResourceManager.GetString("Guardian_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one who believes that sexual interaction should bring intense, almost animalistic experiences, and that you need to be totally in tune with your partner&apos;s energy..
        /// </summary>
        internal static string PassionPursuer_Description {
            get {
                return ResourceManager.GetString("PassionPursuer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passion Pursuer.
        /// </summary>
        internal static string PassionPursuer_Name {
            get {
                return ResourceManager.GetString("PassionPursuer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one that sees physical pleasure as the only objective, considering sex one of the simplest pleasures in life. Likes abundant physical contact, but does not feel the need for the emotional component to do so..
        /// </summary>
        internal static string PleasureSeeker_Description {
            get {
                return ResourceManager.GetString("PleasureSeeker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasure Seeker.
        /// </summary>
        internal static string PleasureSeeker_Name {
            get {
                return ResourceManager.GetString("PleasureSeeker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one who highly values their sex lives and is willing to make sacrifices to maintain a routine, no excuses..
        /// </summary>
        internal static string Prioritizer_Description {
            get {
                return ResourceManager.GetString("Prioritizer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritizer.
        /// </summary>
        internal static string Prioritizer_Name {
            get {
                return ResourceManager.GetString("Prioritizer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one whose sex is based on a deep connection between the two, it is common to maintain eye contact with the partner or tell him that you love him during sexual intercourse..
        /// </summary>
        internal static string Romantic_Description {
            get {
                return ResourceManager.GetString("Romantic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic.
        /// </summary>
        internal static string Romantic_Name {
            get {
                return ResourceManager.GetString("Romantic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To whose sex it is more than what happens in the body, and should be an almost transcendent experience, a communion of souls and not just of bodies..
        /// </summary>
        internal static string Spiritualist_Description {
            get {
                return ResourceManager.GetString("Spiritualist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritualist.
        /// </summary>
        internal static string Spiritualist_Name {
            get {
                return ResourceManager.GetString("Spiritualist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one who sees the sexual act as something exciting, almost forbidden. These are the kind of people who need the taboo element, whether that means experiencing something unusual or satisfying a fetish..
        /// </summary>
        internal static string ThrillSeeker_Description {
            get {
                return ResourceManager.GetString("ThrillSeeker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrill Seeker.
        /// </summary>
        internal static string ThrillSeeker_Name {
            get {
                return ResourceManager.GetString("ThrillSeeker_Name", resourceCulture);
            }
        }
    }
}
