//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SexualOrientation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SexualOrientation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.SexualOrientation", typeof(SexualOrientation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are people who are attracted to both male and female genders provided these people posses both feminine and masculine features i.e. they are androgynous. The attraction mostly depends on the appearance of the person as they need to look both male and female for them to appear attractive to an androgynsexual person..
        /// </summary>
        internal static string Androgynsexual_Description {
            get {
                return ResourceManager.GetString("Androgynsexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androgynsexual.
        /// </summary>
        internal static string Androgynsexual_Name {
            get {
                return ResourceManager.GetString("Androgynsexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term used to communicate sexual or romantic attraction to men, males, or masculinity. This term intentionally includes attraction to those who identify as men, male, or masculine, regardless of biology, anatomy, or sex assigned at birth..
        /// </summary>
        internal static string Androsexual_Description {
            get {
                return ResourceManager.GetString("Androsexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androsexual.
        /// </summary>
        internal static string Androsexual_Name {
            get {
                return ResourceManager.GetString("Androsexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone who identifies as a member of the asexual community experiences little or no sexual attraction to others of any gender. Asexuality is a broad spectrum. People who identify as asexual may also identify with one or more other terms that can more specifically capture their relationship to sexual attraction..
        /// </summary>
        internal static string Asexual_Description {
            get {
                return ResourceManager.GetString("Asexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asexual.
        /// </summary>
        internal static string Asexual_Name {
            get {
                return ResourceManager.GetString("Asexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who’s sexually attracted to themselves. Someone’s desire to engage in sexual behavior such as masturbation doesn’t determine whether they’re autosexual..
        /// </summary>
        internal static string Autosexual_Description {
            get {
                return ResourceManager.GetString("Autosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosexual.
        /// </summary>
        internal static string Autosexual_Name {
            get {
                return ResourceManager.GetString("Autosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sexual orientation that describes people who experience sexual, romantic, or emotional attractions to people of more than one gender..
        /// </summary>
        internal static string Bisexual_Description {
            get {
                return ResourceManager.GetString("Bisexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisexual.
        /// </summary>
        internal static string Bisexual_Name {
            get {
                return ResourceManager.GetString("Bisexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the asexual spectrum, this sexual orientation describes people who experience sexual attraction only under specific circumstances, such as after building a romantic or emotional relationship with a person..
        /// </summary>
        internal static string Demisexual_Description {
            get {
                return ResourceManager.GetString("Demisexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demisexual.
        /// </summary>
        internal static string Demisexual_Name {
            get {
                return ResourceManager.GetString("Demisexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graysexual is used to acknowledge the gray area on the sexuality spectrum for people who don’t explicitly and exclusively identify as asexual or aromantic..
        /// </summary>
        internal static string Graysexual_Description {
            get {
                return ResourceManager.GetString("Graysexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graysexual.
        /// </summary>
        internal static string Graysexual_Name {
            get {
                return ResourceManager.GetString("Graysexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term used to communicate sexual or romantic attraction to women, females, or femininity. This term intentionally includes attraction to those who identify as women, female, or feminine regardless of biology, anatomy, or the sex assigned at birth..
        /// </summary>
        internal static string Gynosexual_Description {
            get {
                return ResourceManager.GetString("Gynosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gynosexual.
        /// </summary>
        internal static string Gynosexual_Name {
            get {
                return ResourceManager.GetString("Gynosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term that describes people who experience sexual, romantic, or emotional attraction to people of the “opposite” gender (e.g., male vs. female, man vs. woman) or a different gender..
        /// </summary>
        internal static string Heterosexual_Description {
            get {
                return ResourceManager.GetString("Heterosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heterosexual.
        /// </summary>
        internal static string Heterosexual_Name {
            get {
                return ResourceManager.GetString("Heterosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term that describes people who experience sexual, romantic, or emotional attraction to people of the same or a similar gender..
        /// </summary>
        internal static string Homosexual_Description {
            get {
                return ResourceManager.GetString("Homosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homosexual.
        /// </summary>
        internal static string Homosexual_Name {
            get {
                return ResourceManager.GetString("Homosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term that describes people who can experience sexual, romantic, or emotional attraction to any person, regardless of that person’s gender, sex, or sexuality..
        /// </summary>
        internal static string Pansexual_Description {
            get {
                return ResourceManager.GetString("Pansexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pansexual.
        /// </summary>
        internal static string Pansexual_Name {
            get {
                return ResourceManager.GetString("Pansexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term that describes people with a sexual orientation that involves sexual or romantic attraction to people with varying genders. Polysexual orientations include bisexuality, pansexuality, omnisexuality, and queer, among many others..
        /// </summary>
        internal static string Polysexual_Description {
            get {
                return ResourceManager.GetString("Polysexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polysexual.
        /// </summary>
        internal static string Polysexual_Name {
            get {
                return ResourceManager.GetString("Polysexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term used to refer to people who reject sexuality labels or don’t identify with any of them. Pomosexual is not necessarily an identity..
        /// </summary>
        internal static string Pomosexual_Description {
            get {
                return ResourceManager.GetString("Pomosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomosexual.
        /// </summary>
        internal static string Pomosexual_Name {
            get {
                return ResourceManager.GetString("Pomosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A word used to describe those who experience attraction based on intelligence, rather than sex or gender..
        /// </summary>
        internal static string Sapiosexual_Description {
            get {
                return ResourceManager.GetString("Sapiosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapiosexual.
        /// </summary>
        internal static string Sapiosexual_Name {
            get {
                return ResourceManager.GetString("Sapiosexual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sexual orientation that describes people who are sexually attracted to those with non-cisgender gender identities, such as people who are nonbinary, genderqueer, or trans..
        /// </summary>
        internal static string Skoliosexual_Description {
            get {
                return ResourceManager.GetString("Skoliosexual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skoliosexual.
        /// </summary>
        internal static string Skoliosexual_Name {
            get {
                return ResourceManager.GetString("Skoliosexual_Name", resourceCulture);
            }
        }
    }
}
