//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SplitTheBill {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SplitTheBill() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.SplitTheBill", typeof(SplitTheBill).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think everything should be paid equally, proportionately or individually (whichever works best for both).
        /// </summary>
        internal static string Balanced_Description {
            get {
                return ResourceManager.GetString("Balanced_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string Balanced_Name {
            get {
                return ResourceManager.GetString("Balanced_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I find it normal to be supported by my partner and/or to receive treats frequently (financial, gifts, etc.).
        /// </summary>
        internal static string Dependent_Description {
            get {
                return ResourceManager.GetString("Dependent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent.
        /// </summary>
        internal static string Dependent_Name {
            get {
                return ResourceManager.GetString("Dependent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I find it normal for my partner to pay most bills/expenses (household, travel, outings, restaurants, etc.) and/or give me gifts from time to time.
        /// </summary>
        internal static string GetGifts_Description {
            get {
                return ResourceManager.GetString("GetGifts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Favors.
        /// </summary>
        internal static string GetGifts_Name {
            get {
                return ResourceManager.GetString("GetGifts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I find it normal to support my partner and/or offer treats frequently (financial, gifts, etc.).
        /// </summary>
        internal static string Provider_Description {
            get {
                return ResourceManager.GetString("Provider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string Provider_Name {
            get {
                return ResourceManager.GetString("Provider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I find it normal to pay most bills/expenses (house, travel, outings, restaurants, etc.) and/or gift my partner from time to time.
        /// </summary>
        internal static string SendGifts_Description {
            get {
                return ResourceManager.GetString("SendGifts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To please.
        /// </summary>
        internal static string SendGifts_Name {
            get {
                return ResourceManager.GetString("SendGifts_Name", resourceCulture);
            }
        }
    }
}
