//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.Sports", typeof(Sports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Football.
        /// </summary>
        internal static string AmericanFootball {
            get {
                return ResourceManager.GetString("AmericanFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archery.
        /// </summary>
        internal static string Archery {
            get {
                return ResourceManager.GetString("Archery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm Wrestling.
        /// </summary>
        internal static string ArmWrestling {
            get {
                return ResourceManager.GetString("ArmWrestling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Racing.
        /// </summary>
        internal static string AutoRacing {
            get {
                return ResourceManager.GetString("AutoRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badminton.
        /// </summary>
        internal static string Badminton {
            get {
                return ResourceManager.GetString("Badminton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseball.
        /// </summary>
        internal static string Baseball {
            get {
                return ResourceManager.GetString("Baseball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMX.
        /// </summary>
        internal static string BMX {
            get {
                return ResourceManager.GetString("BMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bobsledding.
        /// </summary>
        internal static string Bobsledding {
            get {
                return ResourceManager.GetString("Bobsledding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyboarding.
        /// </summary>
        internal static string Bodyboarding {
            get {
                return ResourceManager.GetString("Bodyboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowling.
        /// </summary>
        internal static string Bowling {
            get {
                return ResourceManager.GetString("Bowling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing.
        /// </summary>
        internal static string Boxing {
            get {
                return ResourceManager.GetString("Boxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canoeing.
        /// </summary>
        internal static string Canoeing {
            get {
                return ResourceManager.GetString("Canoeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitive Dancing.
        /// </summary>
        internal static string CompetitiveDancing {
            get {
                return ResourceManager.GetString("CompetitiveDancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cricket.
        /// </summary>
        internal static string Cricket {
            get {
                return ResourceManager.GetString("Cricket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-country Skiing.
        /// </summary>
        internal static string CrossCountrySkiing {
            get {
                return ResourceManager.GetString("CrossCountrySkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curling.
        /// </summary>
        internal static string Curling {
            get {
                return ResourceManager.GetString("Curling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diving.
        /// </summary>
        internal static string Diving {
            get {
                return ResourceManager.GetString("Diving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodgeball.
        /// </summary>
        internal static string Dodgeball {
            get {
                return ResourceManager.GetString("Dodgeball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Boat Racing.
        /// </summary>
        internal static string DragonBoatRacing {
            get {
                return ResourceManager.GetString("DragonBoatRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSports.
        /// </summary>
        internal static string ElectronicSports {
            get {
                return ResourceManager.GetString("ElectronicSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Hockey.
        /// </summary>
        internal static string FieldHockey {
            get {
                return ResourceManager.GetString("FieldHockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure Skating.
        /// </summary>
        internal static string FigureSkating {
            get {
                return ResourceManager.GetString("FigureSkating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footbag (Hacky Sack).
        /// </summary>
        internal static string FootbagHackySack {
            get {
                return ResourceManager.GetString("FootbagHackySack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football (Soccer).
        /// </summary>
        internal static string FootballSoccer {
            get {
                return ResourceManager.GetString("FootballSoccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frisbee.
        /// </summary>
        internal static string Frisbee {
            get {
                return ResourceManager.GetString("Frisbee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gliding.
        /// </summary>
        internal static string Gliding {
            get {
                return ResourceManager.GetString("Gliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        internal static string Golf {
            get {
                return ResourceManager.GetString("Golf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymnastics.
        /// </summary>
        internal static string Gymnastics {
            get {
                return ResourceManager.GetString("Gymnastics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang Gliding.
        /// </summary>
        internal static string HangGliding {
            get {
                return ResourceManager.GetString("HangGliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        internal static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse Racing.
        /// </summary>
        internal static string HorseRacing {
            get {
                return ResourceManager.GetString("HorseRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Fishing.
        /// </summary>
        internal static string IceFishing {
            get {
                return ResourceManager.GetString("IceFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Hockey.
        /// </summary>
        internal static string IceHockey {
            get {
                return ResourceManager.GetString("IceHockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayaking.
        /// </summary>
        internal static string Kayaking {
            get {
                return ResourceManager.GetString("Kayaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacrosse.
        /// </summary>
        internal static string Lacrosse {
            get {
                return ResourceManager.GetString("Lacrosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logrolling.
        /// </summary>
        internal static string Logrolling {
            get {
                return ResourceManager.GetString("Logrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luge.
        /// </summary>
        internal static string Luge {
            get {
                return ResourceManager.GetString("Luge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Arts.
        /// </summary>
        internal static string MartialArts {
            get {
                return ResourceManager.GetString("MartialArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Golf.
        /// </summary>
        internal static string MiniatureGolf {
            get {
                return ResourceManager.GetString("MiniatureGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountaineering.
        /// </summary>
        internal static string Mountaineering {
            get {
                return ResourceManager.GetString("Mountaineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragliding.
        /// </summary>
        internal static string Paragliding {
            get {
                return ResourceManager.GetString("Paragliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polo.
        /// </summary>
        internal static string Polo {
            get {
                return ResourceManager.GetString("Polo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racquetball.
        /// </summary>
        internal static string Racquetball {
            get {
                return ResourceManager.GetString("Racquetball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafting.
        /// </summary>
        internal static string Rafting {
            get {
                return ResourceManager.GetString("Rafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringette.
        /// </summary>
        internal static string Ringette {
            get {
                return ResourceManager.GetString("Ringette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Climbing.
        /// </summary>
        internal static string RockClimbing {
            get {
                return ResourceManager.GetString("RockClimbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller Skating / Inline Skating.
        /// </summary>
        internal static string RollerSkatingInlineSkating {
            get {
                return ResourceManager.GetString("RollerSkatingInlineSkating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowing.
        /// </summary>
        internal static string Rowing {
            get {
                return ResourceManager.GetString("Rowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugby.
        /// </summary>
        internal static string Rugby {
            get {
                return ResourceManager.GetString("Rugby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailing.
        /// </summary>
        internal static string Sailing {
            get {
                return ResourceManager.GetString("Sailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skateboarding.
        /// </summary>
        internal static string Skateboarding {
            get {
                return ResourceManager.GetString("Skateboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skydiving.
        /// </summary>
        internal static string Skydiving {
            get {
                return ResourceManager.GetString("Skydiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snorkelling.
        /// </summary>
        internal static string Snorkelling {
            get {
                return ResourceManager.GetString("Snorkelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowboarding.
        /// </summary>
        internal static string Snowboarding {
            get {
                return ResourceManager.GetString("Snowboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowshoeing.
        /// </summary>
        internal static string Snowshoeing {
            get {
                return ResourceManager.GetString("Snowshoeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squash.
        /// </summary>
        internal static string Squash {
            get {
                return ResourceManager.GetString("Squash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Hockey.
        /// </summary>
        internal static string StreetHockey {
            get {
                return ResourceManager.GetString("StreetHockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumo.
        /// </summary>
        internal static string Sumo {
            get {
                return ResourceManager.GetString("Sumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfing.
        /// </summary>
        internal static string Surfing {
            get {
                return ResourceManager.GetString("Surfing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming.
        /// </summary>
        internal static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tennis.
        /// </summary>
        internal static string TableTennis {
            get {
                return ResourceManager.GetString("TableTennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track &amp; Field.
        /// </summary>
        internal static string TrackField {
            get {
                return ResourceManager.GetString("TrackField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trampolining.
        /// </summary>
        internal static string Trampolining {
            get {
                return ResourceManager.GetString("Trampolining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triathlon.
        /// </summary>
        internal static string Triathlon {
            get {
                return ResourceManager.GetString("Triathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicycling.
        /// </summary>
        internal static string Unicycling {
            get {
                return ResourceManager.GetString("Unicycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volleyball.
        /// </summary>
        internal static string Volleyball {
            get {
                return ResourceManager.GetString("Volleyball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakesurfing.
        /// </summary>
        internal static string Wakesurfing {
            get {
                return ResourceManager.GetString("Wakesurfing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        internal static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Polo.
        /// </summary>
        internal static string WaterPolo {
            get {
                return ResourceManager.GetString("WaterPolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightlifting.
        /// </summary>
        internal static string Weightlifting {
            get {
                return ResourceManager.GetString("Weightlifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windsurfing.
        /// </summary>
        internal static string Windsurfing {
            get {
                return ResourceManager.GetString("Windsurfing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Chopping.
        /// </summary>
        internal static string WoodChopping {
            get {
                return ResourceManager.GetString("WoodChopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrestling.
        /// </summary>
        internal static string Wrestling {
            get {
                return ResourceManager.GetString("Wrestling", resourceCulture);
            }
        }
    }
}
