//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TravelFrequency {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TravelFrequency() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.TravelFrequency", typeof(TravelFrequency).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone who does not travel or travels infrequently (usually on vacation or in specific situations).
        /// </summary>
        internal static string NeverRarely_Description {
            get {
                return ResourceManager.GetString("NeverRarely_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never / Rarely.
        /// </summary>
        internal static string NeverRarely_Name {
            get {
                return ResourceManager.GetString("NeverRarely_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who travels with a certain frequency (between 30% and 70% of their time), either for work or for leisure on weekends.
        /// </summary>
        internal static string SometimesFrequently_Description {
            get {
                return ResourceManager.GetString("SometimesFrequently_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes / Frequently.
        /// </summary>
        internal static string SometimesFrequently_Name {
            get {
                return ResourceManager.GetString("SometimesFrequently_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É alguém que está em constante movimento (muitas vezes não tem residência permanente), como uma estrela do rock que passa 365 dias por ano em ônibus de turismo e quartos de hotel ou um nômade digital que trabalha online e tem liberdade geográfica de viver onde quer..
        /// </summary>
        internal static string UsuallyAlwaysNomad_Description {
            get {
                return ResourceManager.GetString("UsuallyAlwaysNomad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually / Always / Nomad.
        /// </summary>
        internal static string UsuallyAlwaysNomad_Name {
            get {
                return ResourceManager.GetString("UsuallyAlwaysNomad_Name", resourceCulture);
            }
        }
    }
}
