//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerusDate.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TVGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerusDate.Shared.Resources.Enum.TVGenre", typeof(TVGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A programme that features animated characters..
        /// </summary>
        internal static string CartoonAnime_Description {
            get {
                return ResourceManager.GetString("CartoonAnime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime / Cartoon.
        /// </summary>
        internal static string CartoonAnime_Name {
            get {
                return ResourceManager.GetString("CartoonAnime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A television show that features the presentation of food in a kitchen television studio..
        /// </summary>
        internal static string CookingShow_Description {
            get {
                return ResourceManager.GetString("CookingShow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Show.
        /// </summary>
        internal static string CookingShow_Name {
            get {
                return ResourceManager.GetString("CookingShow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A feature or near-feature film depicting a real-world event or person, told in a journalistic style..
        /// </summary>
        internal static string Documentary_Description {
            get {
                return ResourceManager.GetString("Documentary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        internal static string Documentary_Name {
            get {
                return ResourceManager.GetString("Documentary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of program that helps kids learn their basics to go through school..
        /// </summary>
        internal static string Educational_Description {
            get {
                return ResourceManager.GetString("Educational_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational.
        /// </summary>
        internal static string Educational_Name {
            get {
                return ResourceManager.GetString("Educational_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On game shows, teams of competitors or participants called in from the audience try to solve puzzles or answer trivia questions, with prizes awarded if they win..
        /// </summary>
        internal static string GameShow_Description {
            get {
                return ResourceManager.GetString("GameShow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Show.
        /// </summary>
        internal static string GameShow_Name {
            get {
                return ResourceManager.GetString("GameShow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV programmes produced for children..
        /// </summary>
        internal static string KidsChildren_Description {
            get {
                return ResourceManager.GetString("KidsChildren_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids / Children.
        /// </summary>
        internal static string KidsChildren_Name {
            get {
                return ResourceManager.GetString("KidsChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A television show featuring topics such as fashion, diet, exercise, health and leisure pursuits..
        /// </summary>
        internal static string Lifestyle_Description {
            get {
                return ResourceManager.GetString("Lifestyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifestyle.
        /// </summary>
        internal static string Lifestyle_Name {
            get {
                return ResourceManager.GetString("Lifestyle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program where people can listen to music on their TV&apos;s. This is just like a radio station..
        /// </summary>
        internal static string MusicTelevision_Description {
            get {
                return ResourceManager.GetString("MusicTelevision_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Television.
        /// </summary>
        internal static string MusicTelevision_Name {
            get {
                return ResourceManager.GetString("MusicTelevision_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News programming includes local nightly news, national daytime broadcasts on cable networks, and weekly programming that generally airs on Fridays or weekends..
        /// </summary>
        internal static string NewsProgramm_Description {
            get {
                return ResourceManager.GetString("NewsProgramm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Programm.
        /// </summary>
        internal static string NewsProgramm_Name {
            get {
                return ResourceManager.GetString("NewsProgramm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality TV tends to emphasize ordinary people rather than the big stars. Some reality shows are competitions, while others claim to show slices of real life..
        /// </summary>
        internal static string RealityTV_Description {
            get {
                return ResourceManager.GetString("RealityTV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality TV.
        /// </summary>
        internal static string RealityTV_Name {
            get {
                return ResourceManager.GetString("RealityTV_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced by religious organizations, usually with a religious message. May include church services, talk/variety shows, and dramatic films..
        /// </summary>
        internal static string Religious_Description {
            get {
                return ResourceManager.GetString("Religious_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religious.
        /// </summary>
        internal static string Religious_Name {
            get {
                return ResourceManager.GetString("Religious_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone-in TV shows (often on shopping channels), where people can either buy featured items or bid for them..
        /// </summary>
        internal static string Shopping_Description {
            get {
                return ResourceManager.GetString("Shopping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string Shopping_Name {
            get {
                return ResourceManager.GetString("Shopping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A television or radio drama series that typically deals with everyday events in the lives of the same group of characters..
        /// </summary>
        internal static string SoapOpera_Description {
            get {
                return ResourceManager.GetString("SoapOpera_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap Opera.
        /// </summary>
        internal static string SoapOpera_Name {
            get {
                return ResourceManager.GetString("SoapOpera_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike many other formats, sports are often streamed live, bringing a sense of immediacy and urgency to the viewing experience..
        /// </summary>
        internal static string Sports_Description {
            get {
                return ResourceManager.GetString("Sports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string Sports_Name {
            get {
                return ResourceManager.GetString("Sports_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk shows or chat shows are television shows based on discussions between presenters..
        /// </summary>
        internal static string TalkShow_Description {
            get {
                return ResourceManager.GetString("TalkShow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Show.
        /// </summary>
        internal static string TalkShow_Name {
            get {
                return ResourceManager.GetString("TalkShow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group of episodes of a television program broadcast in regular intervals with a long break between each group, usually with one year between the beginning of each..
        /// </summary>
        internal static string TVSeries_Description {
            get {
                return ResourceManager.GetString("TVSeries_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Series.
        /// </summary>
        internal static string TVSeries_Name {
            get {
                return ResourceManager.GetString("TVSeries_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety shows highlight the talent of your guests. Variety shows include musical acts, dancing, stand-up comedy performances and comedy skits..
        /// </summary>
        internal static string VarietyShow_Description {
            get {
                return ResourceManager.GetString("VarietyShow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety Show.
        /// </summary>
        internal static string VarietyShow_Name {
            get {
                return ResourceManager.GetString("VarietyShow_Name", resourceCulture);
            }
        }
    }
}
